// Generated by embed.py

static const char* icons__arrow_down_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <polygon points="79.762,49.965 74.26,44.467 51.889,66.836 51.889,14.27 44.109,14.27 44.109,66.836 21.738,44.467
    16.238,49.965 47.996,81.73 "/>
</g>
</svg>
)~~~~";

static const char* icons__arrow_up_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <polygon points="16.238,46.035 21.74,51.533 44.111,29.164 44.111,81.73 51.891,81.73 51.891,29.164 74.262,51.533
    79.762,46.035 48.004,14.27 "/>
</g>
</svg>
)~~~~";

static const char* icons__checkbox_check_svg = R"~~~~(<svg version="1.1" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96">
<g>
  <rect display="none" x="14.5" y="14.5" fill="none" stroke="#cccccc" stroke-width="4" width="67" height="67"/>
  <polygon fill="#33B3E3" points="94,18.231 85.857,10.086 47.121,49.207 31.59,33.793 23.445,41.94 47.152,65.5 51.297,61.355 51.277,61.338"/>
</g>
</svg>
)~~~~";

static const char* icons__checkbox_nocheck_svg = R"~~~~(<svg version="1.1" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96">
<g>
  <rect x="14.5" y="14.5" fill="none" stroke="#cccccc" stroke-width="4" width="67" height="67"/>
</g>
</svg>
)~~~~";

static const char* icons__chevron_down_svg = R"~~~~(<svg version="1.1" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96">
<g>
  <polygon points="72.628,32.223 48.002,53.488 23.366,32.223 18.278,38.121 48.002,63.777 77.722,38.121 "/>
</g>
</svg>
)~~~~";

static const char* icons__chevron_left_svg = R"~~~~(<svg version="1.1" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96">
<g>
  <polygon points="57.879,18.277 32.223,47.998 57.879,77.723 63.776,72.634 42.512,47.998 63.776,23.372"/>
</g>
</svg>
)~~~~";

static const char* icons__chevron_right_svg = R"~~~~(<svg version="1.1" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96">
<g>
  <polygon points="32.223,23.372 53.488,47.998 32.223,72.634 38.121,77.723 63.777,47.998 38.121,18.277"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_drive_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="512px" height="853px" viewBox="0 0 512 853">
<g id="layer1" transform="translate(0, 171)">
  <path fill="#7F8C8D" d="M465.5,140.2v92.9v92.9v139.4c0,25.2-20.5,46.5-46.5,46.5H92.9c-26,0-46.5-21.3-46.5-46.5V326.9v-93.7v-92.9H465.5z"/>
  <path fill="#95A5A6" d="M46.5,117.4v92.9v92.9v139.4c0,25.2,20.5,46.5,46.5,46.5h326.1c26,0,46.5-21.3,46.5-46.5V303.3v-92.9v-92.9H46.5z"/>
  <rect x="326.1" y="396.2" fill="#7F8C8D" width="116.6" height="92.9"/>
  <path fill="#BDC3C7" d="M92.9,0.8c-26,0-46.5,20.5-46.5,46.5v70.1V141v46.5v45.7v47.3V304v70.1c0,26,20.5,46.5,46.5,46.5h326.1c26,0,46.5-20.5,46.5-46.5V304v-70.9v-92.9v-23.6V46.5c0-26-20.5-46.5-46.5-46.5H92.9V0.8z"/>
  <rect x="348.9" y="442.7" fill="#F1C40F" width="70.1" height="23.6"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_file_svg = R"~~~~(<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns="http://www.w3.org/2000/svg"
   xmlns:xlink="http://www.w3.org/1999/xlink"
   version="1.2"
   x="0px"
   y="0px"
   width="375"
   height="625"
   viewBox="0 0 375 625">
  <g
     id="g4"
     transform="matrix(1.016998,0,0,-0.98596701,0.44339066,500.8413)">
    <linearGradient
       id="SVGID_3_"
       gradientUnits="userSpaceOnUse"
       x1="230.29106"
       y1="288.92206"
       x2="21.064276"
       y2="21.861425">
      <stop
         offset="0"
         style="stop-color:#ffffff;stop-opacity:1;"
         id="stop7" />
      <stop
         offset="1"
         style="stop-color:#d7d7d7;stop-opacity:1;"
         id="stop9" />
    </linearGradient>
    <path fill="url(#SVGID_3_)"
       d="m 350.666,-99.332653 -333.334,0 0,580.749653 186.001,0 c 25.333,0 47.437,-6.145 57.334,-15.306 C 271.376,456.2 292,435.227 298,428.589 c 6,-6.638 32.5,-36.786 40,-48.402 7.5,-11.617 12.666,-33.743 12.666,-61.771 z"
       id="path11" />
    <linearGradient
       id="SVGID_4_"
       gradientUnits="userSpaceOnUse"
       x1="305.91409"
       y1="428.83011"
       x2="288.2449"
       y2="411.16089">
      <stop
         offset="0"
         style="stop-color:#BABABA"
         id="stop14" />
      <stop
         offset="1"
         style="stop-color:#F2F2F2"
         id="stop16" />
    </linearGradient>
    <path fill="url(#SVGID_4_)"
       d="m 272.666,395.122 c 0,0 2,22.496 0,44.99 -1.696,19.085 -19.999,41.305 -69.333,41.305 25.333,0 47.437,-6.145 57.334,-15.306 C 271.376,456.2 292,435.227 298,428.589 c 6,-6.638 32.5,-36.786 40,-48.402 7.5,-11.617 12.666,-33.743 12.666,-61.771 0,54.58 -20.083,74.829 -37.333,76.706 -20.333,2.213 -40.667,0 -40.667,0"
       id="path18" />
  </g>
</svg>
)~~~~";

static const char* icons__ic_folder_svg = R"~~~~(<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="375" height="625" viewBox="0 0 375 625">

  <g id="layer1"
     transform="translate(-245.21,-32.12)">
    <path
       style="fill:#77B5FF;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
       d="M 558.16646,118.40989 265.7806,58.846347 l 0,430.324973 293.39601,59.7693 c 6.58539,1.3416 12.12183,4.5033 12.12183,-9.1473 l 0,-9.3872 c 0,0 -0.98416,-12.5219 16.16242,-9.0289 16.81984,3.4613 16.16241,-9.0289 16.16241,-9.0289 l 5e-5,-113.2876 c 0,0 0.14566,-12.2958 -15.07535,-15.3966 -15.20927,-3.0983 -17.24953,-17.617 -17.24953,-17.617 l 0,-232.33514 c 0.43213,-15.36051 -6.69636,-14.18297 -13.13198,-15.30209 z"
       id="path8" />
    <path
       style="fill:#eeeeee;fill-opacity:1;fill-rule:evenodd;stroke:none"
       d="m 492.12609,654.02805 -0.32735,-397.50449 c 0.23106,-15.23063 -3.58062,-16.29939 -7.02181,-19.4474 L 328.4351,85.332628 l 0,430.502752 156.37364,153.41268 c 8.47181,2.13808 7.76344,-8.45489 7.31735,-15.22001 z"
       transform="matrix(1.2967879,-0.2286578,0,0.9931109,-136.95273,63.111634)" />
    <path
       style="fill:#7EBDFF;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:0.73139018px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
       d="M 421.98813,210.45557 265.64629,58.712037 l 0,430.502783 141.15959,137.31865 c 3.5174,3.4217 10.34784,8.85469 10.34784,-4.80161 0,0 -0.0639,4.91066 -0.0639,-15.32604 l 0,-147.8997 c 0,0 -0.50311,-18.6786 11.9201,-6.6208 l 0,-221.98235 c 0.23106,-15.23063 -3.58062,-16.29939 -7.02181,-19.4474 z" />
  </g>

</svg>
)~~~~";

static const char* icons__ic_menu_accept_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <polygon points="83.277,26.438 79.135,22.293 36.399,65.413 16.867,46 12.722,50.146
    36.43,73.706 40.574,69.563 40.554,69.544 "/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_add_bookmark_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <polygon points="70.449,73.377 70.449,59.951 66.248,59.951 66.248,73.377 53.018,73.377 53.018,77.578
    66.248,77.578 66.248,91 70.449,91 70.449,77.578 83.676,77.578 83.676,73.377 "/>
  <polygon points="22.125,6 22.125,70 40.5,59.696 58.875,70 58.875,6 "/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_add_doc_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <polygon points="73.449,73.377 73.449,59.951 69.248,59.951 69.248,73.377 56.018,73.377 56.018,77.578
    69.248,77.578 69.248,91 73.449,91 73.449,77.578 86.676,77.578 86.676,73.377 "/>
  <path d="M48.425,48.76h-22.68v-2h22.68V48.76z M39.085,42.75h-13.34v-2h13.34V42.75z M43.085,36.75h-17.34v-2h17.34
    V36.75z M49.755,30.75h-24.01v-2h24.01V30.75z M39.085,24.75h-13.34v-2h13.34V24.75z M55.755,11.75h-36.01v48.01h36.01V11.75z
     M13.745,5.74h48.01v60.02h-48.01V5.74z"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_add_folder_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <polygon points="77.449,66.377 77.449,52.951 73.248,52.951 73.248,66.377 60.018,66.377 60.018,70.578
    73.248,70.578 73.248,84 77.449,84 77.449,70.578 90.676,70.578 90.676,66.377 "/>
  <polygon points="66.051,29.678 18.679,29.678 13.839,45.47 12.056,43.94 16.388,27.385 66.051,27.385 66.051,23.565
    33.796,23.565 29.037,14.74 9,14.74 9,61.261 66.051,61.261 75.729,29.678 "/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_add_people_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <path d="M49.985,48.159c9.119,0,16.512-7.392,16.512-16.515c0-9.12-7.392-16.512-16.512-16.512
    c-9.123,0-16.513,7.392-16.513,16.512C33.473,40.768,40.862,48.159,49.985,48.159 M60.954,36.598
    c-2.522,4.894-6.854,8.125-11.774,8.125c-4.925,0-9.252-3.231-11.775-8.125H60.954z M40.02,50.301
    c-6.418,1.684-11.443,5.68-13.748,14.27h47.422c-2.303-8.59-7.331-12.584-13.745-14.27c-2.973,1.594-6.363,2.5-9.963,2.5
    C46.383,52.801,42.99,51.893,40.02,50.301 M30.26,28.894c0.84-6.044,4.391-11.218,9.393-14.266
    c-2.975-4.344-7.967-7.198-13.631-7.198c-9.123,0-16.514,7.392-16.514,16.511c0,9.122,7.391,16.514,16.514,16.514
    c1.979,0,3.869-0.365,5.627-1.003c-0.51-1.19-0.9-2.44-1.172-3.735c-1.625,0.84-3.4,1.301-5.26,1.301
    c-4.923,0-9.252-3.231-11.773-8.124H30.26 M16.057,42.598c-6.42,1.684-11.445,5.678-13.75,14.269H25.73
    c2.697-4.642,6.688-7.774,12.063-9.479c-1.432-1.111-2.705-2.414-3.791-3.865c-2.465,1.011-5.156,1.574-7.98,1.574
    C22.42,45.096,19.025,44.189,16.057,42.598"/>
<polygon points="80.449,69.377 80.449,55.951 76.248,55.951 76.248,69.377 63.018,69.377 63.018,73.578
  76.248,73.578 76.248,87 80.449,87 80.449,73.578 93.676,73.578 93.676,69.377 "/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_add_pic_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <polygon points="74.449,69.92 74.449,56.494 70.248,56.494 70.248,69.92 57.018,69.92 57.018,74.121 70.248,74.121
    70.248,87.543 74.449,87.543 74.449,74.121 87.676,74.121 87.676,69.92 "/>
  <path d="M62.711,8.457H8.324v54.391h54.387V8.457z M59.035,59.174H12.002V12.139h47.033V59.174z"/>
  <polygon points="55.807,47.176 45.581,40.973 37.041,44.803 25.387,34.446 15.682,41.338 15.682,55.08 55.807,55.08"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_append_page_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <polygon points="72.949,70.877 72.949,57.451 68.748,57.451 68.748,70.877 55.518,70.877 55.518,75.078
    68.748,75.078 68.748,88.5 72.949,88.5 72.949,75.078 86.176,75.078 86.176,70.877 "/>
  <polygon points="32.223,23.372 53.488,47.998 32.223,72.634 38.121,77.723 63.777,47.998 38.121,18.277"/>
  <!-- polygon points="73.762,45.965 68.26,40.467 45.889,62.836 45.889,10.27 38.109,10.27 38.109,62.836 15.738,40.467
    10.238,45.965 41.996,77.73 "/ -->
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_back_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <polygon points="46.031,79.76 51.531,74.258 29.162,51.885 81.73,51.885 81.73,44.11 29.162,44.11 51.531,21.739
    46.031,16.24 14.27,47.998 "/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_bookmark_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <polygon points="27.788,12.8 27.788,83.2 48,71.866 68.212,83.2 68.212,12.8"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_cancel_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <polygon points="74.854,25.288 70.712,21.145 48,43.856 25.289,21.145 21.146,25.288 43.856,48
    21.146,70.712 25.289,74.854 48,52.144 70.712,74.854 74.854,70.712 52.145,48 "/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_clock_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
  x="0px" y="0px" width="96px" height="96px" viewBox="0 0 24 24" xml:space="preserve">
<g class="icon">
  <path d="M11.99 2C6.47 2 2 6.48 2 12s4.47 10 9.99 10C17.52 22 22 17.52 22 12S17.52 2 11.99 2zM12 20c-4.42 0-8-3.58-8-8s3.58-8 8-8 8 3.58 8 8-3.58 8-8 8z"/>
  <path d="M12.5 7H11v6l5.25 3.15.75-1.23-4.5-2.67z"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_cloud_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<defs> <style type="text/css"><![CDATA[
  .coloricon { fill: #2841D5; }
]]></style> </defs>
<g class="coloricon">
<path fill-rule="evenodd" d="M77.921,50.825C77.319,42.66,70.518,36.22,62.198,36.22
  c-3.216,0-6.204,0.965-8.706,2.622c-1.794-7.016-8.14-12.209-15.714-12.209c-8.967,0-16.238,7.277-16.238,16.244
  c0,0.661,0.051,1.309,0.125,1.953c-0.09-0.003-0.181-0.019-0.275-0.019c-6.78,0-12.279,5.501-12.279,12.282
  c0,6.569,5.173,11.926,11.666,12.243v0.03H77.23V69.33c0.123,0.004,0.242,0.037,0.369,0.037c5.134,0,9.29-4.159,9.29-9.289
  C86.89,55.057,82.904,50.996,77.921,50.825"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_copy_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <path style="fill-rule:evenodd;" d="M60.005,17.99h-36.01v48.02h3v6h-3h-6V11.99h48.01v6v3h-6V17.99z
     M64.675,67.01h-22.68v-2h22.68V67.01z M55.335,61h-13.34v-2h13.34V61z M59.335,55h-17.34v-2h17.34V55z M66.005,49h-24.01v-2h24.01
    V49z M55.335,43h-13.34v-2h13.34V43z M72.005,30h-36.01v48.01h36.01V30z M29.995,23.99h48.01v60.02h-48.01V23.99z"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_cut_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <path d="M78.76,61.816c0.781,0.569,1.25,1.49,1.25,2.459c0,0.65-0.199,1.271-0.59,1.801
    c-0.48,0.66-1.189,1.09-2,1.209c-0.799,0.131-1.609-0.069-2.27-0.549c-0.779-0.57-1.24-1.5-1.24-2.471c0-0.65,0.199-1.27,0.59-1.8
    C75.49,61.115,77.4,60.816,78.76,61.816 M57.01,48.256c0-1.321,1.07-2.391,2.391-2.391c1.311,0,2.379,1.07,2.379,2.391
    c0,1.31-1.068,2.379-2.379,2.379C58.08,50.636,57.01,49.566,57.01,48.256 M77.42,29.216c0.811,0.13,1.52,0.559,2,1.21
    c0.391,0.529,0.59,1.15,0.59,1.799c0,0.97-0.469,1.901-1.25,2.47c-0.66,0.481-1.459,0.681-2.27,0.551
    c-0.801-0.12-1.51-0.551-1.99-1.211c-0.391-0.529-0.59-1.149-0.59-1.799c0-0.971,0.461-1.89,1.24-2.461
    C75.811,29.285,76.621,29.096,77.42,29.216 M72.779,26.535c-1.059,0.771-1.959,1.98-2.389,2.83c-0.221,0.441-0.52,0.971-0.9,1.631
    c-0.33,0.59-0.73,1.289-1.199,2.149c-2.451,4.5-4.941,7.431-4.961,7.451c-0.02,0.019-1.391,1.589-2.91,2.95
    c-8.5-3.651-22.419-9.591-23.76-9.931c-2-0.5-3.91,0.91-3.99,0.971l-0.879,0.66l0.939,0.57l20.49,12.44L32.73,60.686l-0.939,0.57
    l0.879,0.66c0.08,0.06,1.99,1.47,3.99,0.97c1.33-0.329,15.26-6.28,23.76-9.931c1.52,1.371,2.891,2.94,2.9,2.951
    c0.029,0.029,2.52,2.949,4.971,7.459c0.469,0.86,0.869,1.561,1.209,2.15c0.371,0.66,0.67,1.18,0.891,1.62
    c0.43,0.851,1.33,2.06,2.389,2.84c3.141,2.3,7.58,1.621,9.881-1.521c0.891-1.219,1.359-2.648,1.359-4.159
    c0-2.229-1.07-4.36-2.859-5.699c-0.77-0.571-1.65-0.981-2.48-1.171c-0.67-0.24-1.18-0.32-1.719-0.41
    c-0.801-0.14-1.701-0.29-3.521-1.02c-3.539-1.42-6.5-4.051-6.549-4.101c-0.861-0.72-1.701-1.979-2.441-3.639
    c0.74-1.67,1.58-2.93,2.461-3.67c0.029-0.02,2.98-2.651,6.529-4.071c1.82-0.73,2.721-0.889,3.521-1.019
    c0.539-0.09,1.049-0.18,1.648-0.391c0.9-0.219,1.781-0.63,2.57-1.199c1.781-1.34,2.84-3.461,2.84-5.69
    c0-1.511-0.469-2.951-1.359-4.16C80.35,24.916,75.92,24.225,72.779,26.535"/>
  <polygon points="59.98,78 17.98,78 17.98,18 59.98,18 59.98,30 65.98,30 65.98,12
    11.98,12 11.98,84 59.98,84 65.98,84 65.98,66 59.98,66   "/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_discard_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <path d="M68.917,41.842c-0.046-0.281-0.218-0.557-0.476-0.82
    c-2.079,2.112-10.444,2.462-20.445,2.462s-18.358-0.35-20.446-2.462c-0.257,0.263-0.417,0.539-0.476,0.82h-0.019l0.006,0.152
    c0,0.018-0.006,0.036-0.006,0.054c0,0.041,0.011,0.077,0.017,0.116L28.7,75.518h0.004c0.145,2.615,3.139,6.568,19.292,6.568
    c16.155,0,19.151-3.953,19.292-6.568H67.3l1.63-33.354c0.003-0.039,0.016-0.075,0.016-0.116c0-0.018-0.013-0.036-0.013-0.054
    l0.013-0.152H68.917z"/>
  <path d="M57.95,24.386v-7.875c0-1.422-1.164-2.597-2.595-2.597H39.769
    c-1.421,0-2.59,1.175-2.59,2.597v7.965c-7.706,0.874-12.981,2.644-12.981,4.694v3.893c0,0.799,0.809,1.559,2.26,2.244
    c3.801,1.786,12.017,3.024,21.538,3.024c9.528,0,17.741-1.238,21.547-3.024c1.442-0.685,2.259-1.445,2.259-2.244v-3.893
    C71.802,27.048,66.12,25.221,57.95,24.386 M42.161,24.06l-0.657,0.041v-3.262c0-1.426,0.199-2.594,0.434-2.594h3.032h5.193h3.027
    c0.239,0,0.435,1.168,0.435,2.594v3.209c-1.806-0.093-3.685-0.152-5.629-0.152C45.981,23.896,44.024,23.955,42.161,24.06"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_document_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <path d="M61.599,15.805H21.74v64.39h52.52v-64.39H61.599z M68.378,69.199H27.624v-3.672h40.754V69.199z
     M68.378,59.652H27.462v-3.834h40.916V59.652z M68.541,49.945H27.624v-3.999h40.917V49.945z M68.541,39.911H27.624v-3.668h40.917
    V39.911z M68.541,30.203H27.624v-3.672h40.917V30.203z"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_drawer_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="-64 -64 640 640" xml:space="preserve">
<g class="icon">
    <path d="M449.247,0l33.622,285.779l-37.739,4.44L415.104,35H96.896L66.87,290.221l-37.74-4.44L62.75,0H449.247z M128,64h256v32H128
    V64z M128,128h256v32H128V128z M128,192h256v32H128V192z M128,256h256v32H128V256z M496,320H16c-8.8,0-13.723,6.83-10.94,15.18
    l53.88,161.643C61.723,505.17,71.2,512,80,512h352c8.8,0,18.275-6.83,21.06-15.179l53.882-161.645
    C509.724,326.83,504.8,320,496,320z M320,384H192v-32h128V384z"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_draw_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
  x="0px" y="0px" width="96px" height="96px" viewBox="0 0 24 24" xml:space="preserve">
<g class="icon stroked" stroke="currentColor">
  <path stroke-width="1" d="M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25z
    M20.71 7.04c.39-.39.39-1.02 0-1.41l-2.34-2.34c-.39-.39-1.02-.39-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_duplicate_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="-2 -2 28 28" xml:space="preserve">
<g class="icon">
    <path d="M3 5H1v16c0 1.1.9 2 2 2h16v-2H3V5zm18-4H7c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V3c0-1.1-.9-2-2-2zm0 16H7V3h14v14zm-4-4h-4v-2h2c1.1 0 2-.89 2-2V7c0-1.11-.9-2-2-2h-4v2h4v2h-2c-1.1 0-2 .89-2 2v4h6v-2z"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_editbox_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <path d="M16,67.47h64V28.53H16V67.47z M75.824,63.249H20.178V32.707h55.646V63.249z"/>
  <rect x="25" y="35" width="3.5" height="26"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_ellipsis_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <rect x="63.074" y="40.589" width="14.996" height="14.986"/>
  <rect x="40.081" y="40.589" width="14.996" height="14.986"/>
  <rect x="18.088" y="40.589" width="14.995" height="14.986"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_erase_free_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <path d="M 84,27 V 12 H 69 l -44.24,44.24 15,15 z M 13.16,67.84 c -1.56,1.56 -1.56,4.08 0,5.64 l 9.36,9.36 c 1.56,1.56 4.08,1.56 5.64,0 l 7.32,-7.32 -15,-15 z"/>
</g>
<g class="icon stroked" fill="none" stroke="currentColor" stroke-linecap="round">
  <path stroke-width="8" d="M10.479,10c0,0-1.229,6.75,2.521,14c3.547,6.858,15,15,15,15"/>
  <path stroke-width="8" d="M85.808,86c0,0,1.229-6.75-2.521-14c-3.547-6.858-15-15-15-15"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_erase_ruled_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <g>
    <path d="M 84,27 V 12 H 69 l -44.24,44.24 15,15 z M 13.16,67.84 c -1.56,1.56 -1.56,4.08 0,5.64 l 9.36,9.36 c 1.56,1.56 4.08,1.56 5.64,0 l 7.32,-7.32 -15,-15 z"/>
  </g>
  <polygon points="14.381,37.7 14.381,41.7 81.619,41.7 81.604,37.7 "/>
  <polygon points="14.381,57.7 14.381,61.7 81.619,61.7 81.604,57.7 "/>
  <polygon points="14.381,77.7 14.381,81.7 81.619,81.7 81.604,77.7 "/>
  <polygon points="14.381,17.7 14.381,21.7 81.619,21.7 81.604,17.7 "/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_erase_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <path d="M 84,27 V 12 H 69 l -44.24,44.24 15,15 z M 13.16,67.84 c -1.56,1.56 -1.56,4.08 0,5.64 l 9.36,9.36 c 1.56,1.56 4.08,1.56 5.64,0 l 7.32,-7.32 -15,-15 z"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_expanddown_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <rect x="24.75" y="45.76" width="24.564" height="2"/>
  <rect x="24.75" y="39.75" width="14.448" height="2"/>
  <rect x="24.75" y="33.75" width="18.781" height="2"/>
  <rect x="24.75" y="27.75" width="26.005" height="2"/>
  <rect x="24.75" y="21.75" width="14.448" height="2"/>
</g>
<g class="icon stroked" fill="none" stroke="currentColor">
  <rect stroke-width="4" x="16.745" y="11.74" width="42.01" height="72.927"/>
</g>
<g class="icon stroked dashed" fill="none" stroke="currentColor">
  <line stroke-width="4" stroke-dasharray="4,3" x1="18" y1="58.75" x2="56.875" y2="58.75"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_expandright_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <rect x="24.75" y="45.76" width="24.564" height="2"/>
  <rect x="24.75" y="39.75" width="14.448" height="2"/>
  <rect x="24.75" y="33.75" width="18.781" height="2"/>
  <rect x="24.75" y="27.75" width="26.005" height="2"/>
  <rect x="24.75" y="21.75" width="14.448" height="2"/>
</g>
<g class="icon stroked" fill="none" stroke="currentColor">
  <rect stroke-width="4" x="16.745" y="11.74" width="62.385" height="47.01"/>
</g>
<g class="icon stroked dashed" fill="none" stroke="currentColor">
  <line stroke-width="4" stroke-dasharray="4,3" x1="58.755" y1="56.875" x2="58.755" y2="13.5"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_folder_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <polygon points="78.762,37.192 17.24,37.192 10.954,57.701 8.639,55.715 14.264,34.214 78.762,34.214 78.762,29.254
    36.873,29.254 30.692,17.792 4.67,17.792 4.67,78.209 78.762,78.209 91.33,37.192 "/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_forward_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <polygon points="49.965,16.238 44.467,21.74 66.836,44.111 14.27,44.111 14.27,51.891 66.836,51.891 44.467,74.262
    49.965,79.762 81.73,48.004 "/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_fullscreen_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
  x="0px" y="0px" width="96px" height="96px" viewBox="0 0 24 24" xml:space="preserve">
<g class="icon">
  <path d="M7 14H5v5h5v-2H7v-3zm-2-4h2V7h3V5H5v5zm12 7h-3v2h5v-5h-2v3zM14 5v2h3v3h2V5h-5z"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_help_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <path d="M40.103,58.048v-3.06c0-1.406,0.145-2.681,0.435-3.825
    c0.289-1.144,0.729-2.232,1.322-3.267c0.594-1.033,1.358-2.039,2.295-3.018c0.937-0.978,2.068-1.992,3.391-3.039
    c1.158-0.91,2.136-1.723,2.935-2.44c0.8-0.716,1.447-1.427,1.943-2.13c0.496-0.702,0.855-1.439,1.076-2.211
    c0.221-0.771,0.33-1.669,0.33-2.688c0-1.572-0.531-2.868-1.592-3.887c-1.062-1.021-2.682-1.53-4.858-1.53
    c-1.903,0-3.949,0.4-6.141,1.199c-2.19,0.8-4.459,1.778-6.802,2.936l-4.218-9.138c1.185-0.689,2.474-1.344,3.867-1.964
    c1.392-0.621,2.839-1.172,4.341-1.654s3.025-0.862,4.569-1.137c1.544-0.276,3.06-0.414,4.549-0.414
    c2.812,0,5.347,0.339,7.608,1.013c2.261,0.676,4.177,1.661,5.747,2.957c1.572,1.295,2.777,2.868,3.619,4.713
    c0.84,1.848,1.261,3.956,1.261,6.327c0,1.736-0.193,3.288-0.579,4.652c-0.386,1.363-0.957,2.633-1.715,3.804
    c-0.76,1.172-1.71,2.302-2.854,3.39c-1.145,1.089-2.475,2.24-3.99,3.453c-1.158,0.91-2.103,1.704-2.834,2.378
    c-0.73,0.675-1.302,1.315-1.715,1.922c-0.414,0.607-0.696,1.235-0.848,1.882c-0.151,0.647-0.228,1.412-0.228,2.294v2.481H40.103z
     M38.738,72.189c0-1.295,0.186-2.391,0.559-3.287c0.371-0.896,0.888-1.619,1.549-2.171c0.662-0.552,1.441-0.95,2.337-1.198
    c0.895-0.249,1.853-0.373,2.873-0.373c0.965,0,1.882,0.124,2.75,0.373c0.867,0.248,1.633,0.646,2.295,1.198
    c0.661,0.552,1.185,1.275,1.57,2.171c0.387,0.896,0.58,1.992,0.58,3.287c0,1.241-0.193,2.302-0.58,3.184
    c-0.386,0.883-0.909,1.613-1.57,2.192c-0.662,0.578-1.428,0.998-2.295,1.261c-0.868,0.262-1.785,0.393-2.75,0.393
    c-1.02,0-1.978-0.131-2.873-0.393c-0.896-0.263-1.675-0.683-2.337-1.261c-0.661-0.579-1.178-1.31-1.549-2.192
    C38.924,74.491,38.738,73.431,38.738,72.189"/></g>
</svg>
)~~~~";

static const char* icons__ic_menu_insert_space_ruled_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <polygon points="14.381,33.7 14.381,37.7 81.619,37.7 81.604,33.7 "/>
  <polygon points="14.381,55.7 14.381,59.7 81.619,59.7 81.604,55.7 "/>
  <path d="M14.381,75.493v6.014h67.238l-0.016-6.014H14.381z M47.716,69.654L31.349,47.329h10.209V26.493h12.213v20.836h10.313L47.716,69.654z"/>
  <polygon points="14.381,12.993 14.381,19.007 81.619,19.007 81.604,12.993 "/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_insert_space_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <path d="M14.381,75.493v6.014h67.238l-0.016-6.014H14.381z M47.716,69.654L31.349,47.329h10.209V26.493h12.213
    v20.836h10.313L47.716,69.654z"/>
  <polygon points="14.381,12.993 14.381,19.007 81.619,19.007 81.604,12.993 "/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_link_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="-32 -32 576 576" xml:space="preserve">
<g class="icon">
  <path d="M459.654,233.373l-90.531,90.5c-49.969,50-131.031,50-181,0c-7.875-7.844-14.031-16.688-19.438-25.813   l42.063-42.063c2-2.016,4.469-3.172,6.828-4.531c2.906,9.938,7.984,19.344,15.797,27.156c24.953,24.969,65.563,24.938,90.5,0   l90.5-90.5c24.969-24.969,24.969-65.563,0-90.516c-24.938-24.953-65.531-24.953-90.5,0l-32.188,32.219   c-26.109-10.172-54.25-12.906-81.641-8.891l68.578-68.578c50-49.984,131.031-49.984,181.031,0   C509.623,102.342,509.623,183.389,459.654,233.373z M220.326,382.186l-32.203,32.219c-24.953,24.938-65.563,24.938-90.516,0   c-24.953-24.969-24.953-65.563,0-90.531l90.516-90.5c24.969-24.969,65.547-24.969,90.5,0c7.797,7.797,12.875,17.203,15.813,27.125   c2.375-1.375,4.813-2.5,6.813-4.5l42.063-42.047c-5.375-9.156-11.563-17.969-19.438-25.828c-49.969-49.984-131.031-49.984-181.016,0   l-90.5,90.5c-49.984,50-49.984,131.031,0,181.031c49.984,49.969,131.031,49.969,181.016,0l68.594-68.594   C274.561,395.092,246.42,392.342,220.326,382.186z"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_minus_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <polygon points="83.049,45.069 12.951,45.069 12.951,50.931 83.049,50.931 "/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_next_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <!-- polygon points="79.762,49.965 74.26,44.467 51.889,66.836 51.889,14.27 44.109,14.27 44.109,66.836 21.738,44.467
    16.238,49.965 47.996,81.73 "/ -->
  <polygon points="32.223,23.372 53.488,47.998 32.223,72.634 38.121,77.723 63.777,47.998 38.121,18.277"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_no_save_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <polygon points="67.447,14.779 60.795,14.779 60.795,25.87 69.666,16.999   "/>
  <polygon points="29.861,56.805 32.611,54.055 29.861,54.055   "/>
  <path d="M57.742,45.592h13.094v31.094H26.65l-4.535,4.535h56.803c1.082,0,1.959-0.877,1.959-1.959V28.215l-2.879-2.88  L57.742,45.592z"/>
  <path d="M25.164,45.592h15.91l7.057-7.057H25.164V14.779h-8.08c-1.085,0-1.961,0.878-1.961,1.961v54.803l10.041-10.041V45.592z"/>
  <polygon points="64.844,65.055 38.28,65.055 34.357,68.979 64.844,68.979 "/>
  <polygon points="64.844,54.055 49.279,54.055 45.358,57.977 64.844,57.977   "/>
  <polygon points="55.129,17.407 41.524,17.407 41.524,34.895 51.771,34.895 55.129,31.536   "/>
  <polygon points="82.079,8.85 86.17,12.942 47.483,51.607 13.921,85.15 9.831,81.057 "/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_overflow_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <rect x="40.586" y="63.077" width="14.986" height="14.996"/>
  <rect x="40.586" y="40.084" width="14.986" height="14.996"/>
  <rect x="40.586" y="18.091" width="14.986" height="14.995"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_pagesel_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <path d="M68.71,84h-3.771v-4h3.771V84z M61.18,84h-3.77v-4h3.77V84z M53.65,84h-3.771v-4h3.771V84z M38.59,84h-3.77
    v-4h3.77V84z M31.061,84H27.29v-4h3.771V84z M12,12h4v4h-4V12z M12,19.76h4v3.771h-4V19.76z M12,27.29h4v3.77h-4V27.29z M12,34.82h4
    v3.77h-4V34.82z M12,42.35h4v3.77h-4V42.35z M12,49.88h4v3.771h-4V49.88z M12,57.41h4v3.77h-4V57.41z M12,64.939h4v3.771h-4V64.939z
     M12,72.471h4v3.771h-4V72.471z M12,80h4v4h-4V80z M19.76,12h3.77v4h-3.77V12z M19.76,80h3.77v4h-3.77V80z M27.29,12h3.771v4H27.29
    V12z M34.82,12h3.77v4h-3.77V12z M42.35,12h3.771v4H42.35V12z M42.35,80h3.771v4H42.35V80z M49.88,12h3.771v4H49.88V12z M57.41,12
    h3.77v4h-3.77V12z M64.939,12h3.771v4h-3.771V12z M72.471,12h3.771v4h-3.771V12z M72.471,80h3.771v4h-3.771V80z M80,12h4v4h-4V12z
     M80,19.76h4v3.771h-4V19.76z M80,27.29h4v3.77h-4V27.29z M80,34.82h4v3.77h-4V34.82z M80,42.35h4v3.77h-4V42.35z M80,49.88h4v3.771
    h-4V49.88z M80,57.41h4v3.77h-4V57.41z M80,64.939h4v3.771h-4V64.939z M80,72.471h4v3.771h-4V72.471z M80,80h4v4h-4V80z"/>

  <rect x="34.75" y="57.76" width="24.564" height="2"/>
  <rect x="34.75" y="51.75" width="14.448" height="2"/>
  <rect x="34.75" y="45.75" width="18.781" height="2"/>
  <rect x="34.75" y="39.75" width="26.005" height="2"/>
  <rect x="34.75" y="33.75" width="14.448" height="2"/>
</g>
<g class="icon stroked" fill="none" stroke="currentColor">
  <rect stroke-width="4" x="26.745" y="23.74" width="42.01" height="47.01"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_pan_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="-4 -4 32 32">
<g class="icon">
  <path d="M23 5.5V20c0 2.2-1.8 4-4 4h-7.3c-1.08 0-2.1-.43-2.85-1.19L1 14.83s1.26-1.23 1.3-1.25c.22-.19.49-.29.79-.29.22 0 .42.06.6.16.04.01 4.31 2.46 4.31 2.46V4c0-.83.67-1.5 1.5-1.5S11 3.17 11 4v7h1V1.5c0-.83.67-1.5 1.5-1.5S15 .67 15 1.5V11h1V2.5c0-.83.67-1.5 1.5-1.5s1.5.67 1.5 1.5V11h1V5.5c0-.83.67-1.5 1.5-1.5s1.5.67 1.5 1.5z"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_paste_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <path style="fill-rule:evenodd" d="M64.005,67h-34.01v-2h34.01V67z M49.995,61h-20v-2h20V61z M56.005,55h-26.01v-2h26.01
    V55z M66.005,49h-36.01v-2h36.01V49z M49.995,43h-20v-2h20V43z M72.005,20.99h-14l1.16,3.49c5.52,1.211,6.84,4.56,6.84,8.51h-36.01
    c0-3.76,1.56-6.969,6.77-8.309l1.23-3.691h-14v60.02h48.01V20.99z M47.995,11.99c-1.65,0-3,1.34-3,3c0,1.65,1.35,3,3,3
    c1.66,0,3-1.35,3-3C50.995,13.33,49.655,11.99,47.995,11.99 M17.995,87.01V14.99h24c0-3.32,2.689-6,6-6c3.32,0,6.01,2.68,6.01,6h24
    v72.02H17.995z"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_people_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <path d="M36.014,60.159c9.123,0,16.513-7.392,16.513-16.515c0-9.12-7.39-16.512-16.513-16.512
    c-9.12,0-16.511,7.392-16.511,16.512C19.503,52.768,26.895,60.159,36.014,60.159 M48.595,48.598
    c-2.523,4.893-6.85,8.125-11.775,8.125c-4.921,0-9.252-3.232-11.774-8.125H48.595z M45.98,62.301c-2.97,1.592-6.363,2.5-9.966,2.5
    c-3.599,0-6.99-0.906-9.962-2.5c-6.415,1.686-11.443,5.68-13.746,14.27h47.422C57.424,67.98,52.398,63.984,45.98,62.301
     M55.74,40.894h16.816c-2.521,4.892-6.85,8.124-11.773,8.124c-1.859,0-3.635-0.462-5.26-1.301
    c-0.271,1.295-0.662,2.545-1.172,3.735c1.758,0.638,3.648,1.003,5.627,1.003c9.123,0,16.514-7.392,16.514-16.514
    c0-9.119-7.391-16.511-16.514-16.511c-5.664,0-10.656,2.854-13.631,7.198C51.35,29.676,54.9,34.85,55.74,40.894 M69.943,54.598
    c-2.969,1.592-6.363,2.498-9.965,2.498c-2.824,0-5.515-0.564-7.98-1.574c-1.086,1.451-2.359,2.754-3.791,3.865
    c5.375,1.705,9.365,4.838,12.063,9.479h23.424C81.389,60.275,76.363,56.281,69.943,54.598"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_pin_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
  x="0px" y="0px" width="96px" height="96px" viewBox="-4 -4 32 32" xml:space="preserve">
<g class="icon">
  <path d="M16,12V4H17V2H7V4H8V12L6,14V16H11.2V22H12.8V16H18V14L16,12Z" />
  <!-- slashed pin: d="M2,5.27L3.28,4L20,20.72L18.73,22L12.8,16.07V22H11.2V16H6V14L8,12V11.27L2,5.27M16,12L18,14V16H17.82L8,6.18V4H7V2H17V4H16V12Z" -->
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_plus_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <polygon points="83.049,45.069 50.931,45.069 50.931,12.951 45.07,12.951 45.07,45.069
    12.951,45.069 12.951,50.931 45.07,50.931 45.07,83.048 50.931,83.048 50.931,50.931 83.049,50.931 "/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_preferences_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <path d="M32.115,34.997c-2.81,0-5.121,2.3-5.121,5.121v15.765
    c0,2.82,2.311,5.121,5.121,5.121h1.76c2.811,0,5.122-2.301,5.122-5.121V40.118c0-2.821-2.311-5.121-5.122-5.121H32.115z
     M62.124,59.004c-2.811,0-5.121,2.299-5.121,5.121v15.764c0,2.822,2.311,5.121,5.121,5.121h1.761c2.81,0,5.122-2.299,5.122-5.121
    V64.125c0-2.822-2.313-5.121-5.122-5.121H62.124z M62.124,10.99c-2.811,0-5.121,2.301-5.121,5.121v15.765
    c0,2.821,2.311,5.122,5.121,5.122h1.761c2.821,0,5.122-2.301,5.122-5.122V16.111c0-2.82-2.301-5.121-5.122-5.121H62.124z
     M54.002,21.993H11.989v4.001h42.013V21.993z M84.011,21.993H72.007v4.001h12.004V21.993z M23.992,46H11.989v4h12.003V46z
     M84.011,46H41.998v4h42.013V46z M54.002,70.006H11.989v4.002h42.013V70.006z M84.011,70.006H72.007v4.002h12.004V70.006z"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_prev_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <!-- polygon points="16.238,46.035 21.74,51.533 44.111,29.164 44.111,81.73 51.891,81.73 51.891,29.164 74.262,51.533
    79.762,46.035 48.004,14.27 "/ -->
  <polygon points="57.879,18.277 32.223,47.998 57.879,77.723 63.776,72.634 42.512,47.998 63.776,23.372"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_redo_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <path d="M43.148,40c-22.086,0-27.373,15.467-28.59,21.645l15.229,8.24c0-2.519,0.866-6.097,2.274-8.24
    c2.521-3.85,6.832-5.674,11.03-5.674h7.897v22.043l30.45-30.026L50.99,17.986V40H43.148"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_refresh_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <path style="fill-rule:evenodd;" d="M58.986,24.938c-5.547-2.447-11.825-2.83-17.658-0.982
    c-11.08,3.488-18.276,14.001-17.529,25.577l-7.561,0.493c-0.98-15.07,8.4-28.758,22.805-33.307
    c8.441-2.659,17.58-1.739,25.344,2.456l7.258-7.753l1.932,21.512l-22.787,0.758L58.986,24.938z M58.705,79.11
    c-3.193,1.001-6.51,1.506-9.805,1.506c-5.369,0-10.695-1.384-15.508-3.973l-7.267,7.765l-1.931-21.513l22.774-0.766l-8.187,8.763
    c5.539,2.437,11.816,2.821,17.65,0.98c11.078-3.498,18.285-14.021,17.527-25.576l7.563-0.496
    C82.512,60.854,73.131,74.552,58.705,79.11"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_save_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <path d="M55.129,34.895H41.524V17.407h13.605V34.895z M64.844,54.055H29.861v3.921
    h34.983V54.055z M64.844,65.055H29.861v3.923h34.983V65.055z M80.877,28.215v51.047c0,1.082-0.877,1.959-1.959,1.959H17.084
    c-1.085,0-1.961-0.877-1.961-1.959V16.74c0-1.083,0.876-1.961,1.961-1.961h8.08v23.756h35.631V14.779h6.652L80.877,28.215z
     M70.836,45.592H25.164v31.093h45.672V45.592z"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_select_lasso_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <rect x="27" y="51" width="18" height="18"/>
  <rect x="27" y="27" width="18" height="18"/>
  <rect x="51" y="27" width="18" height="18"/>
  <rect x="51" y="51" width="18" height="18"/>
</g>
<g class="icon stroked" fill="none" stroke="currentColor">
  <!-- 2*pi*r should be multiple of stroke-dasharray -->
  <circle stroke-width="4" stroke-dasharray="4" cx="48" cy="48" r="34.377"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_select_path_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96">
<g class="icon">
  <path d="M25 51h20v20h-20v-20 m3 3v14h14v-14h-14"/>
  <path d="M51 25h20v20h-20v-20 m3 3v14h14v-14h-14"/>
</g>
<g class="icon">
  <rect x="25" y="25" width="20" height="20"/>
  <rect x="51" y="51" width="20" height="20"/>
</g>
<g class="icon stroked" fill="none" stroke="currentColor">
  <path d="m13 13c6.3 10.3 13.2 25.6 35 35s35 35 35 35" stroke-dasharray="4" stroke-width="4"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_select_ruled_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <path d="M68.71,84h-3.771v-4h3.771V84z M61.18,84h-3.77v-4h3.77V84z M53.65,84h-3.771v-4h3.771V84z M38.59,84h-3.77
    v-4h3.77V84z M31.061,84H27.29v-4h3.771V84z M12,12h4v4h-4V12z M12,19.76h4v3.771h-4V19.76z M12,27.29h4v3.77h-4V27.29z M12,34.82h4
    v3.77h-4V34.82z M12,42.35h4v3.77h-4V42.35z M12,49.88h4v3.771h-4V49.88z M12,57.41h4v3.77h-4V57.41z M12,64.939h4v3.771h-4V64.939z
     M12,72.471h4v3.771h-4V72.471z M12,80h4v4h-4V80z M19.76,12h3.77v4h-3.77V12z M19.76,80h3.77v4h-3.77V80z M27.29,12h3.771v4H27.29
    V12z M34.82,12h3.77v4h-3.77V12z M42.35,12h3.771v4H42.35V12z M42.35,80h3.771v4H42.35V80z M49.88,12h3.771v4H49.88V12z M57.41,12
    h3.77v4h-3.77V12z M64.939,12h3.771v4h-3.771V12z M72.471,12h3.771v4h-3.771V12z M72.471,80h3.771v4h-3.771V80z M80,12h4v4h-4V12z
     M80,19.76h4v3.771h-4V19.76z M80,27.29h4v3.77h-4V27.29z M80,34.82h4v3.77h-4V34.82z M80,42.35h4v3.77h-4V42.35z M80,49.88h4v3.771
    h-4V49.88z M80,57.41h4v3.77h-4V57.41z M80,64.939h4v3.771h-4V64.939z M80,72.471h4v3.771h-4V72.471z M80,80h4v4h-4V80z"/>
  <polygon points="18.5,39.7 18.5,43.7 77.5,43.7 77.486,39.7 "/>
  <polygon points="18.5,51.7 18.5,55.7 77.5,55.7 77.486,51.7 "/>
  <polygon points="18.5,63.7 18.5,67.7 58.007,67.7 57.997,63.7 "/>
  <polygon points="41.875,27.7 41.875,31.7 77.5,31.7 77.492,27.7 "/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_select_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
<path d="M68.71,84h-3.771v-4h3.771V84z M61.18,84h-3.77v-4h3.77V84z M53.65,84h-3.771v-4h3.771
  V84z M38.59,84h-3.77v-4h3.77V84z M31.061,84H27.29v-4h3.771V84z M45,69H27V51h18V69z M12,12h4v4h-4V12z M12,19.76h4v3.77h-4V19.76z
   M12,27.29h4v3.77h-4V27.29z M12,34.82h4v3.77h-4V34.82z M12,42.35h4v3.77h-4V42.35z M12,49.88h4v3.771h-4V49.88z M12,57.41h4v3.77
  h-4V57.41z M12,64.939h4v3.771h-4V64.939z M12,72.471h4v3.771h-4V72.471z M12,80h4v4h-4V80z M19.76,12h3.77v4h-3.77V12z M19.76,80
  h3.77v4h-3.77V80z M45,45H27V27h18V45z M27.29,12h3.771v4H27.29V12z M34.82,12h3.77v4h-3.77V12z M42.35,12h3.771v4H42.35V12z
   M42.35,80h3.771v4H42.35V80z M49.88,12h3.771v4H49.88V12z M57.41,12h3.77v4h-3.77V12z M64.939,12h3.771v4h-3.771V12z M51,27h18v18
  H51V27z M51,51h18v18H51V51z M72.471,12h3.771v4h-3.771V12z M72.471,80h3.771v4h-3.771V80z M80,12h4v4h-4V12z M80,19.76h4v3.77h-4
  V19.76z M80,27.29h4v3.77h-4V27.29z M80,34.82h4v3.77h-4V34.82z M80,42.35h4v3.77h-4V42.35z M80,49.88h4v3.771h-4V49.88z M80,57.41
  h4v3.77h-4V57.41z M80,64.939h4v3.771h-4V64.939z M80,72.471h4v3.771h-4V72.471z M80,80h4v4h-4V80z"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_send_now_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <polygon points="20.242,75.404 25.529,50.484 58.842,48.167 58.842,47.83 25.529,45.513 20.242,20.595 75.758,48.002 "/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_send_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <polygon points="14.918,37.94 14.918,72.551 81.082,72.551 81.082,37.94 47.999,54.389 "/>
  <polygon points="14.918,23.449 14.918,32.658 47.999,49.102 81.082,32.658 81.082,23.449 "/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_separator_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <polygon points="45.685,80 50.315,80 50.315,16 45.685,16.015 "/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_set_pen_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 24 24" xml:space="preserve">
<g class="icon">
  <path d="M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25z M20.71 7.04c.39-.39.39-1.02 0-1.41l-2.34-2.34c-.39-.39-1.02-.39-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z"/>
  <path transform="translate(13 13) scale(0.36)" d="M19.43 12.98c.04-.32.07-.64.07-.98s-.03-.66-.07-.98l2.11-1.65c.19-.15.24-.42.12-.64l-2-3.46c-.12-.22-.39-.3-.61-.22l-2.49 1c-.52-.4-1.08-.73-1.69-.98l-.38-2.65C14.46 2.18 14.25 2 14 2h-4c-.25 0-.46.18-.49.42l-.38 2.65c-.61.25-1.17.59-1.69.98l-2.49-1c-.23-.09-.49 0-.61.22l-2 3.46c-.13.22-.07.49.12.64l2.11 1.65c-.04.32-.07.65-.07.98s.03.66.07.98l-2.11 1.65c-.19.15-.24.42-.12.64l2 3.46c.12.22.39.3.61.22l2.49-1c.52.4 1.08.73 1.69.98l.38 2.65c.03.24.24.42.49.42h4c.25 0 .46-.18.49-.42l.38-2.65c.61-.25 1.17-.59 1.69-.98l2.49 1c.23.09.49 0 .61-.22l2-3.46c.12-.22.07-.49-.12-.64l-2.11-1.65zM12 15.5c-1.93 0-3.5-1.57-3.5-3.5s1.57-3.5 3.5-3.5 3.5 1.57 3.5 3.5-1.57 3.5-3.5 3.5z"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_settings_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
  x="0px" y="0px" width="96px" height="96px" viewBox="0 0 24 24" xml:space="preserve">
<g class="icon">
  <path d="M19.43 12.98c.04-.32.07-.64.07-.98s-.03-.66-.07-.98l2.11-1.65c.19-.15.24-.42.12-.64l-2-3.46c-.12-.22-.39-.3-.61-.22l-2.49 1c-.52-.4-1.08-.73-1.69-.98l-.38-2.65C14.46 2.18 14.25 2 14 2h-4c-.25 0-.46.18-.49.42l-.38 2.65c-.61.25-1.17.59-1.69.98l-2.49-1c-.23-.09-.49 0-.61.22l-2 3.46c-.13.22-.07.49.12.64l2.11 1.65c-.04.32-.07.65-.07.98s.03.66.07.98l-2.11 1.65c-.19.15-.24.42-.12.64l2 3.46c.12.22.39.3.61.22l2.49-1c.52.4 1.08.73 1.69.98l.38 2.65c.03.24.24.42.49.42h4c.25 0 .46-.18.49-.42l.38-2.65c.61-.25 1.17-.59 1.69-.98l2.49 1c.23.09.49 0 .61-.22l2-3.46c.12-.22.07-.49-.12-.64l-2.11-1.65zM12 15.5c-1.93 0-3.5-1.57-3.5-3.5s1.57-3.5 3.5-3.5 3.5 1.57 3.5 3.5-1.57 3.5-3.5 3.5z"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_share_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <path d="M69.916,60.883c-3.232,0-6.123,1.44-8.088,3.704L36.375,50.893c0.26-0.921,0.408-1.888,0.408-2.893
    c0-1.005-0.148-1.971-0.408-2.891l25.453-13.696c1.965,2.264,4.855,3.705,8.088,3.705c5.898,0,10.695-4.793,10.695-10.666
    c0-5.897-4.797-10.693-10.695-10.693c-5.904,0-10.699,4.796-10.699,10.693c0,1.003,0.148,1.97,0.41,2.891L34.16,41.017
    c-1.962-2.251-4.85-3.678-8.078-3.678c-5.898,0-10.693,4.758-10.693,10.661s4.795,10.661,10.693,10.661
    c3.228,0,6.116-1.426,8.08-3.68l25.465,13.677c-0.262,0.921-0.41,1.888-0.41,2.888c0,5.899,4.795,10.695,10.699,10.695
    c5.898,0,10.695-4.796,10.695-10.695C80.611,65.674,75.814,60.883,69.916,60.883"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_split_bt_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
  x="0px" y="0px" width="96px" height="96px" viewBox="0 0 48 48" xml:space="preserve">
<g class="icon">
  <path d="M6 6v36h36V6H6z M9 12h30v12h-30z M9 26h30v13h-30z"/>
  <path d="M24.9 17 l0,-3.6 -1.8,0 0,3.6 -3.6,0 0,1.8 3.6,0 0,3.6 1.8,0 0,-3.6 3.6,0 0,-1.8 -3.6,0" />
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_split_lr_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
  x="0px" y="0px" width="96px" height="96px" viewBox="0 0 48 48" xml:space="preserve">
<g class="icon">
  <path d="M6 6v36h36V6H6z M9 12h14v27h-14z M25 12h14v27h-14z"/>
  <path d="M32.9 25.4 l0,-3.6 -1.8,0 0,3.6 -3.6,0 0,1.8 3.6,0 0,3.6 1.8,0 0,-3.6 3.6,0 0,-1.8 -3.6,0" />
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_split_rl_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
  x="0px" y="0px" width="96px" height="96px" viewBox="0 0 48 48" xml:space="preserve">
<g class="icon">
  <path d="M6 6v36h36V6H6z M9 12h14v27h-14z M25 12h14v27h-14z"/>
  <path d="M16.9 25.4 l0,-3.6 -1.8,0 0,3.6 -3.6,0 0,1.8 3.6,0 0,3.6 1.8,0 0,-3.6 3.6,0 0,-1.8 -3.6,0" />
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_split_tb_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
  x="0px" y="0px" width="96px" height="96px" viewBox="0 0 48 48" xml:space="preserve">
<g class="icon">
  <path d="M6 6v36h36V6H6z M9 12h30v12h-30z M9 26h30v13h-30z"/>
  <path d="M24.9 31.5 l0,-3.6 -1.8,0 0,3.6 -3.6,0 0,1.8 3.6,0 0,3.6 1.8,0 0,-3.6 3.6,0 0,-1.8 -3.6,0" />
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_stretch_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
   x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g class="icon">
  <path d="M78.34,48.513l-17.19,12.602v-7.86H45.106V43.85h16.043v-7.941L78.34,48.513z"/>
  <polygon points="82.835,73.887 87.466,73.887 87.466,22.113 82.835,22.125 "/>
  <path d="M35.346,35.908v7.941h16.044v9.404H35.346v7.86l-17.19-12.602L35.346,35.908z"/>
  <polygon points="9.295,73.887 13.926,73.887 13.926,22.113 9.295,22.125 "/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_undo_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
  x="0px" y="0px" width="96px" height="96px" viewBox="0 0 24 24" xml:space="preserve">
<g class="icon">
  <path d="M12.5 8c-2.65 0-5.05.99-6.9 2.6L2 7v9h9l-3.62-3.62c1.39-1.16 3.16-1.88 5.12-1.88
    3.54 0 6.55 2.31 7.6 5.5l2.37-.78C21.08 11.03 17.15 8 12.5 8z"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_menu_zoom_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
  x="0px" y="0px" width="96px" height="96px" viewBox="0 0 24 24" xml:space="preserve">
<g class="icon">
  <path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"/>
</g>
</svg>
)~~~~";

static const char* icons__ic_scroll_handle_svg = R"~~~~(<?xml version="1.0" encoding="utf-8"?>
<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
  x="0px" y="0px" width="96px" height="96px" viewBox="0 0 96 96" xml:space="preserve">
<g>
  <path fill="#000000" d="M0,0 L96,0 96,96 0,96 Z M23.371,41.777 L47.998,20.512 72.634,41.777 77.721,35.881
    47.998,10.222 18.279,35.881 Z M72.629,54.223 L48.002,75.488 23.366,54.223 18.279,60.119 48.002,85.777 77.722,60.119 Z" />
  <polygon fill="#FFFFFF" points="23.371,41.777 47.998,20.512 72.634,41.777 77.721,35.881 47.998,10.222 18.279,35.881" />
  <polygon fill="#FFFFFF" points="72.629,54.223 48.002,75.488 23.366,54.223 18.279,60.119 48.002,85.777 77.722,60.119" />
</g>
</svg>
)~~~~";

static const char* icons__write_icon_flat_svg = R"~~~~(<?xml version="1.0" encoding="UTF-8"?>
<svg width="228" height="228" version="1.0" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 228 228">
 <defs>
  <linearGradient id="linearGradient3258" x1="14.069" x2="14.143" y1="14.623" y2="8.8007" gradientTransform="matrix(4.1729 4.1729 -9.9065 9.9065 113.78 171.45)" gradientUnits="userSpaceOnUse">
   <stop stop-opacity=".52344" offset="0"/>
   <stop stop-color="#fff" stop-opacity=".78039" offset="1"/>
  </linearGradient>
  <linearGradient id="linearGradient3254" x1="43.549" x2="48.452" y1="52.405" y2="43.595" gradientTransform="matrix(4.3531 0 0 4.3531 -6.0063 281.37)" gradientUnits="userSpaceOnUse">
   <stop stop-color="#2b2b2b" stop-opacity=".67188" offset="0"/>
   <stop stop-opacity=".58594" offset=".28481"/>
   <stop stop-color="#333" stop-opacity="0" offset="1"/>
  </linearGradient>
 </defs>
 <g transform="translate(-11.5956 -299.19)">
  <g transform="matrix(4.7034 4.7034 -4.5224 4.5224 151.98 208.99)" fill="#02126d">
   <path transform="matrix(.61897 0 0 .69686 27.512 20.444)" d="m13.728 10.978v-7.4452l5.3994 3.1173c0.43545 0.25651 0.47055 0.91841 0.04141 1.1866l-5.4408 3.1413z" fill="#2841D5"/>
  </g>
  <path d="m81.794 315.24c-9.4755-0.54649-23.471 6.4667-35.641 18.637-16.227 16.227-23.079 35.687-15.372 43.395 1.8121 1.8121 4.2961 2.7281 7.2098 2.9927l-1.4964-1.4964c0.05742-0.0775 0.06817-0.2042 0.13603-0.27207 0.29914-0.29914 0.74102-0.44467 1.2243-0.54413 1.5075-0.31024 3.9937 0.30158 7.0737 1.7684 8.7789-1.9406 19.589-8.2986 29.247-17.956 16.227-16.227 23.079-35.687 15.372-43.395-1.9269-1.9269-4.5954-2.9466-7.7539-3.1288z" fill="#112281"/>
  <g transform="matrix(4.7034 4.7034 -4.7034 4.7034 157.77 203.2)" fill="#2841d5">
   <path transform="matrix(.46276 -.46276 .46276 .46276 -11.452 29.489)" d="m26.562 8.9688-10 10 28.5 28.5 10 -10z"/>
  </g>
  <path d="m89.571 318.43-14.698 14.698 122.58 122.58 11.611-11.611-1.9107-8.0839-9.8476-9.8476z" fill="#99A5EB"/>
  <path d="m45.414 362.58-14.692 14.692 108.28 108.15 9.3863 9.3863 0.4081 0.13604 9.5224 2.1765 10.883-10.883z" fill="#19277E"/>
  <path d="m207.15 436.02c0.56722 5.6736-4.1562 12.487-15.139 14.257-4.6476 18.645-14.167 27.345-29.249 29.543-2.957 12.851-6.502 15.461-14.257 15.139l49.238 11.317c0.52884-3.1385 5.0469-8.2122 8.8009-11.966 3.7541-3.7541 9.2954-8.3241 12.07-8.9049z" fill="#fd5"/>
<!-- Gradients don't render correctly in usvg!  Fix this!
   <g>
    <path d="m207.15 436.02c0.56722 5.6736-4.1562 12.487-15.139 14.257-4.6476 18.645-14.167 27.345-29.249 29.543-2.957 12.851-6.502 15.461-14.257 15.139l49.238 11.317c0.52884-3.1385 5.0469-8.2122 8.8009-11.966 3.7541-3.7541 9.2954-8.3241 12.07-8.9049z" fill="url(#linearGradient3254)"/>
    <path d="m30.779 377.22c-7.7116-7.7116-0.80205-27.124 15.433-43.359 16.235-16.235 35.647-23.144 43.359-15.433l-29.396 29.396z" fill="url(#linearGradient3258)"/>
   </g>
-->
  <path d="m81.871 315.24c-12.561 0.0261-23.54 7.8688-32.648 15.78 5.8367-2.2938 11.508-5.2226 17.923-4.0247 6.1332 1.1452 4.4966 4.2585 7.7531 5.9979 3.5275-3.5275 11.198-11.097 14.725-14.624-2.0264-2.0528-4.9276-2.9823-7.7539-3.1288z" fill="#3D4B98"/>
 </g>
</svg>
)~~~~";

static void LOAD_RES_FN() { addStringResources({
  {"icons/arrow_down.svg", icons__arrow_down_svg},
  {"icons/arrow_up.svg", icons__arrow_up_svg},
  {"icons/checkbox_check.svg", icons__checkbox_check_svg},
  {"icons/checkbox_nocheck.svg", icons__checkbox_nocheck_svg},
  {"icons/chevron_down.svg", icons__chevron_down_svg},
  {"icons/chevron_left.svg", icons__chevron_left_svg},
  {"icons/chevron_right.svg", icons__chevron_right_svg},
  {"icons/ic_drive.svg", icons__ic_drive_svg},
  {"icons/ic_file.svg", icons__ic_file_svg},
  {"icons/ic_folder.svg", icons__ic_folder_svg},
  {"icons/ic_menu_accept.svg", icons__ic_menu_accept_svg},
  {"icons/ic_menu_add_bookmark.svg", icons__ic_menu_add_bookmark_svg},
  {"icons/ic_menu_add_doc.svg", icons__ic_menu_add_doc_svg},
  {"icons/ic_menu_add_folder.svg", icons__ic_menu_add_folder_svg},
  {"icons/ic_menu_add_people.svg", icons__ic_menu_add_people_svg},
  {"icons/ic_menu_add_pic.svg", icons__ic_menu_add_pic_svg},
  {"icons/ic_menu_append_page.svg", icons__ic_menu_append_page_svg},
  {"icons/ic_menu_back.svg", icons__ic_menu_back_svg},
  {"icons/ic_menu_bookmark.svg", icons__ic_menu_bookmark_svg},
  {"icons/ic_menu_cancel.svg", icons__ic_menu_cancel_svg},
  {"icons/ic_menu_clock.svg", icons__ic_menu_clock_svg},
  {"icons/ic_menu_cloud.svg", icons__ic_menu_cloud_svg},
  {"icons/ic_menu_copy.svg", icons__ic_menu_copy_svg},
  {"icons/ic_menu_cut.svg", icons__ic_menu_cut_svg},
  {"icons/ic_menu_discard.svg", icons__ic_menu_discard_svg},
  {"icons/ic_menu_document.svg", icons__ic_menu_document_svg},
  {"icons/ic_menu_drawer.svg", icons__ic_menu_drawer_svg},
  {"icons/ic_menu_draw.svg", icons__ic_menu_draw_svg},
  {"icons/ic_menu_duplicate.svg", icons__ic_menu_duplicate_svg},
  {"icons/ic_menu_editbox.svg", icons__ic_menu_editbox_svg},
  {"icons/ic_menu_ellipsis.svg", icons__ic_menu_ellipsis_svg},
  {"icons/ic_menu_erase_free.svg", icons__ic_menu_erase_free_svg},
  {"icons/ic_menu_erase_ruled.svg", icons__ic_menu_erase_ruled_svg},
  {"icons/ic_menu_erase.svg", icons__ic_menu_erase_svg},
  {"icons/ic_menu_expanddown.svg", icons__ic_menu_expanddown_svg},
  {"icons/ic_menu_expandright.svg", icons__ic_menu_expandright_svg},
  {"icons/ic_menu_folder.svg", icons__ic_menu_folder_svg},
  {"icons/ic_menu_forward.svg", icons__ic_menu_forward_svg},
  {"icons/ic_menu_fullscreen.svg", icons__ic_menu_fullscreen_svg},
  {"icons/ic_menu_help.svg", icons__ic_menu_help_svg},
  {"icons/ic_menu_insert_space_ruled.svg", icons__ic_menu_insert_space_ruled_svg},
  {"icons/ic_menu_insert_space.svg", icons__ic_menu_insert_space_svg},
  {"icons/ic_menu_link.svg", icons__ic_menu_link_svg},
  {"icons/ic_menu_minus.svg", icons__ic_menu_minus_svg},
  {"icons/ic_menu_next.svg", icons__ic_menu_next_svg},
  {"icons/ic_menu_no_save.svg", icons__ic_menu_no_save_svg},
  {"icons/ic_menu_overflow.svg", icons__ic_menu_overflow_svg},
  {"icons/ic_menu_pagesel.svg", icons__ic_menu_pagesel_svg},
  {"icons/ic_menu_pan.svg", icons__ic_menu_pan_svg},
  {"icons/ic_menu_paste.svg", icons__ic_menu_paste_svg},
  {"icons/ic_menu_people.svg", icons__ic_menu_people_svg},
  {"icons/ic_menu_pin.svg", icons__ic_menu_pin_svg},
  {"icons/ic_menu_plus.svg", icons__ic_menu_plus_svg},
  {"icons/ic_menu_preferences.svg", icons__ic_menu_preferences_svg},
  {"icons/ic_menu_prev.svg", icons__ic_menu_prev_svg},
  {"icons/ic_menu_redo.svg", icons__ic_menu_redo_svg},
  {"icons/ic_menu_refresh.svg", icons__ic_menu_refresh_svg},
  {"icons/ic_menu_save.svg", icons__ic_menu_save_svg},
  {"icons/ic_menu_select_lasso.svg", icons__ic_menu_select_lasso_svg},
  {"icons/ic_menu_select_path.svg", icons__ic_menu_select_path_svg},
  {"icons/ic_menu_select_ruled.svg", icons__ic_menu_select_ruled_svg},
  {"icons/ic_menu_select.svg", icons__ic_menu_select_svg},
  {"icons/ic_menu_send_now.svg", icons__ic_menu_send_now_svg},
  {"icons/ic_menu_send.svg", icons__ic_menu_send_svg},
  {"icons/ic_menu_separator.svg", icons__ic_menu_separator_svg},
  {"icons/ic_menu_set_pen.svg", icons__ic_menu_set_pen_svg},
  {"icons/ic_menu_settings.svg", icons__ic_menu_settings_svg},
  {"icons/ic_menu_share.svg", icons__ic_menu_share_svg},
  {"icons/ic_menu_split_bt.svg", icons__ic_menu_split_bt_svg},
  {"icons/ic_menu_split_lr.svg", icons__ic_menu_split_lr_svg},
  {"icons/ic_menu_split_rl.svg", icons__ic_menu_split_rl_svg},
  {"icons/ic_menu_split_tb.svg", icons__ic_menu_split_tb_svg},
  {"icons/ic_menu_stretch.svg", icons__ic_menu_stretch_svg},
  {"icons/ic_menu_undo.svg", icons__ic_menu_undo_svg},
  {"icons/ic_menu_zoom.svg", icons__ic_menu_zoom_svg},
  {"icons/ic_scroll_handle.svg", icons__ic_scroll_handle_svg},
  {"icons/write_icon_flat.svg", icons__write_icon_flat_svg}
}); }
#undef LOAD_RES_FN

